version: '3.4'

volumes:
  l2_data:

services:
  op-geth:
    build:
      context: .
    ports:
      - "8545:8545"
      - "6060:6060"
      - "30303:30303"
      - "30303:30303/udp"
    volumes:
      - "l2_data:/db"
      - "./genesis.json:/genesis.json"
      - "./test-jwt-secret.txt:/config/test-jwt-secret.txt"
      - "./entrypoint.sh:/entrypoint.sh"
    entrypoint: 
      - "/bin/sh"
      - "/entrypoint.sh"
      - "--authrpc.jwtsecret=/config/test-jwt-secret.txt"
      - "--bootnodes=enode://4d12f8f99cf20c54505146f194f7906a970443ad8ffc6ae6ba79323fb15ff228af256753eefdca0c441283499d9d49a0a7409812eed27a1283b2b5370c685a2d@13.229.130.239:32785"
      - "--verbosity=4"

    environment:
      GETH_MINER_RECOMMIT: 100ms

